version: '3.8'

services:
  survey-back:
    build:
      context: .
      dockerfile: Dockerfile
    image: uzorovkirill/survey-back-image:latest
    container_name: backend
    depends_on:
      - quest-postgres
    environment:
      - REST_API_AI_AGENT_ANALYZE_FULL_ADDRESS=http://ai-analyzer:8000/analyze
      - REST_API_AI_AGENT_ANALYZE_PARAMETER_ADDRESS=http://ai-analyzer:8000/analyze_param?param_code=
      - POSTGRES_ADDRESS=Host=quest-postgres;Port=5432;Database=quest;Username=postgres;Password=quest-system;Timeout=10;CommandTimeout=30;Keepalive=1
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "17311:8080"
    networks:
      - analyzer_net

  quest-postgres:
    container_name: quest-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: quest-system
      POSTGRES_DB: quest
    networks:
      - analyzer_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "17303:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - analyzer_net
    volumes:
      - grafana-storage:/var/lib/grafana


networks:
  analyzer_net:
    driver: bridge

volumes:
  grafana-storage:



